language: csharp
mono: none
dotnet: 2.2.101
dist: xenial
install:
  - dotnet restore
script:
  - dotnet test
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
cache:
  directories:
  - $HOME/.nuget/packages